# Header
menu:
    Home: /
    About: about/
    Open-Source: open-source/
    Blog: blog/
    Contact: contato/

# Profile
profile:
    location: Maceió-AL, Brazil
    github: fromdenisvieira
    #stackoverflow:
        #title: yumemor
        #href: http://stackoverflow.com/users/5662132/yumemor
    #organization: 组织/公司

#Widget
sidebar: false
navfixed: true

#WidgetText
excerpt_link: Read More

#Github(请务必配置github帐号)
github:
  popular_repos: ['cordova-plugin-alipay','hexo-theme-primer']
  #contribute_repos: ['yumemor/1','yumemor/2']

#Comments
comments:
    duoshuo_username:

#Source Code
source_code: https://github.com/fromdenisvieira/fromdenisvieira.github.io
